// Les 77 communes du Bénin, groupées par département — dataset écrit à la
// main (aucun package npm Node/TS utilisable trouvé ; zakiyou/benin-geo est
// un package Laravel/PHP, pas applicable ici). Même esprit que
// src/lib/countries.ts (i18n-iso-countries) : une liste statique plutôt
// qu'un appel réseau pour une donnée qui ne change jamais.
export const BENIN_COMMUNES: { commune: string; departement: string }[] = [
  { commune: "Banikoara", departement: "Alibori" },
  { commune: "Gogounou", departement: "Alibori" },
  { commune: "Kandi", departement: "Alibori" },
  { commune: "Karimama", departement: "Alibori" },
  { commune: "Malanville", departement: "Alibori" },
  { commune: "Ségbana", departement: "Alibori" },
  { commune: "Boukoumbé", departement: "Atakora" },
  { commune: "Cobly", departement: "Atakora" },
  { commune: "Kérou", departement: "Atakora" },
  { commune: "Kouandé", departement: "Atakora" },
  { commune: "Matéri", departement: "Atakora" },
  { commune: "Natitingou", departement: "Atakora" },
  { commune: "Péhunco", departement: "Atakora" },
  { commune: "Tanguiéta", departement: "Atakora" },
  { commune: "Toucountouna", departement: "Atakora" },
  { commune: "Abomey-Calavi", departement: "Atlantique" },
  { commune: "Allada", departement: "Atlantique" },
  { commune: "Kpomassè", departement: "Atlantique" },
  { commune: "Ouidah", departement: "Atlantique" },
  { commune: "Sô-Ava", departement: "Atlantique" },
  { commune: "Toffo", departement: "Atlantique" },
  { commune: "Tori-Bossito", departement: "Atlantique" },
  { commune: "Zè", departement: "Atlantique" },
  { commune: "Bembèrèkè", departement: "Borgou" },
  { commune: "Kalalé", departement: "Borgou" },
  { commune: "N'Dali", departement: "Borgou" },
  { commune: "Nikki", departement: "Borgou" },
  { commune: "Parakou", departement: "Borgou" },
  { commune: "Pèrèrè", departement: "Borgou" },
  { commune: "Sinendé", departement: "Borgou" },
  { commune: "Tchaourou", departement: "Borgou" },
  { commune: "Bantè", departement: "Collines" },
  { commune: "Dassa-Zoumè", departement: "Collines" },
  { commune: "Glazoué", departement: "Collines" },
  { commune: "Ouèssè", departement: "Collines" },
  { commune: "Savalou", departement: "Collines" },
  { commune: "Savè", departement: "Collines" },
  { commune: "Bassila", departement: "Donga" },
  { commune: "Copargo", departement: "Donga" },
  { commune: "Djougou", departement: "Donga" },
  { commune: "Ouaké", departement: "Donga" },
  { commune: "Aplahoué", departement: "Kouffo" },
  { commune: "Djakotomey", departement: "Kouffo" },
  { commune: "Klouékanmè", departement: "Kouffo" },
  { commune: "Lalo", departement: "Kouffo" },
  { commune: "Toviklin", departement: "Kouffo" },
  { commune: "Dogbo-Tota", departement: "Kouffo" },
  { commune: "Cotonou", departement: "Littoral" },
  { commune: "Athiémé", departement: "Mono" },
  { commune: "Bopa", departement: "Mono" },
  { commune: "Comè", departement: "Mono" },
  { commune: "Grand-Popo", departement: "Mono" },
  { commune: "Houéyogbé", departement: "Mono" },
  { commune: "Lokossa", departement: "Mono" },
  { commune: "Adjarra", departement: "Ouémé" },
  { commune: "Adjohoun", departement: "Ouémé" },
  { commune: "Aguégués", departement: "Ouémé" },
  { commune: "Akpro-Missérété", departement: "Ouémé" },
  { commune: "Avrankou", departement: "Ouémé" },
  { commune: "Bonou", departement: "Ouémé" },
  { commune: "Dangbo", departement: "Ouémé" },
  { commune: "Porto-Novo", departement: "Ouémé" },
  { commune: "Sèmè-Kpodji", departement: "Ouémé" },
  { commune: "Ifangni", departement: "Plateau" },
  { commune: "Adja-Ouèrè", departement: "Plateau" },
  { commune: "Kétou", departement: "Plateau" },
  { commune: "Pobè", departement: "Plateau" },
  { commune: "Sakété", departement: "Plateau" },
  { commune: "Abomey", departement: "Zou" },
  { commune: "Agbangnizoun", departement: "Zou" },
  { commune: "Bohicon", departement: "Zou" },
  { commune: "Covè", departement: "Zou" },
  { commune: "Djidja", departement: "Zou" },
  { commune: "Ouinhi", departement: "Zou" },
  { commune: "Za-Kpota", departement: "Zou" },
  { commune: "Zagnanado", departement: "Zou" },
  { commune: "Zogbodomey", departement: "Zou" },
];

export function getCommuneList(): { commune: string; departement: string }[] {
  return BENIN_COMMUNES;
}
